/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedTagsRouteImport } from './routes/_authed.tags'
import { Route as AuthedSubscribersRouteImport } from './routes/_authed.subscribers'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedReadersRouteImport } from './routes/_authed.readers'
import { Route as AuthedMediaRouteImport } from './routes/_authed.media'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed.posts.index'
import { Route as AuthedPostsNewRouteImport } from './routes/_authed.posts.new'
import { Route as AuthedPostsSlugEditRouteImport } from './routes/_authed.posts.$slug.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTagsRoute = AuthedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubscribersRoute = AuthedSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReadersRoute = AuthedReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMediaRoute = AuthedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsNewRoute = AuthedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsSlugEditRoute = AuthedPostsSlugEditRouteImport.update({
  id: '/posts/$slug/edit',
  path: '/posts/$slug/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/media': typeof AuthedMediaRoute
  '/readers': typeof AuthedReadersRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscribers': typeof AuthedSubscribersRoute
  '/tags': typeof AuthedTagsRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/posts/$slug/edit': typeof AuthedPostsSlugEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/media': typeof AuthedMediaRoute
  '/readers': typeof AuthedReadersRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscribers': typeof AuthedSubscribersRoute
  '/tags': typeof AuthedTagsRoute
  '/': typeof AuthedIndexRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/posts/$slug/edit': typeof AuthedPostsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/media': typeof AuthedMediaRoute
  '/_authed/readers': typeof AuthedReadersRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/subscribers': typeof AuthedSubscribersRoute
  '/_authed/tags': typeof AuthedTagsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/posts/new': typeof AuthedPostsNewRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/posts/$slug/edit': typeof AuthedPostsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/media'
    | '/readers'
    | '/settings'
    | '/subscribers'
    | '/tags'
    | '/posts/new'
    | '/posts/'
    | '/posts/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/media'
    | '/readers'
    | '/settings'
    | '/subscribers'
    | '/tags'
    | '/'
    | '/posts/new'
    | '/posts'
    | '/posts/$slug/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/media'
    | '/_authed/readers'
    | '/_authed/settings'
    | '/_authed/subscribers'
    | '/_authed/tags'
    | '/_authed/'
    | '/_authed/posts/new'
    | '/_authed/posts/'
    | '/_authed/posts/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tags': {
      id: '/_authed/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthedTagsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/subscribers': {
      id: '/_authed/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AuthedSubscribersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/readers': {
      id: '/_authed/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof AuthedReadersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/media': {
      id: '/_authed/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthedMediaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/new': {
      id: '/_authed/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthedPostsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$slug/edit': {
      id: '/_authed/posts/$slug/edit'
      path: '/posts/$slug/edit'
      fullPath: '/posts/$slug/edit'
      preLoaderRoute: typeof AuthedPostsSlugEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedMediaRoute: typeof AuthedMediaRoute
  AuthedReadersRoute: typeof AuthedReadersRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSubscribersRoute: typeof AuthedSubscribersRoute
  AuthedTagsRoute: typeof AuthedTagsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPostsNewRoute: typeof AuthedPostsNewRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
  AuthedPostsSlugEditRoute: typeof AuthedPostsSlugEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMediaRoute: AuthedMediaRoute,
  AuthedReadersRoute: AuthedReadersRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSubscribersRoute: AuthedSubscribersRoute,
  AuthedTagsRoute: AuthedTagsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPostsNewRoute: AuthedPostsNewRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
  AuthedPostsSlugEditRoute: AuthedPostsSlugEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
