/**
 * Sinh messages/en.json (sync khung theo vi.json) + src/i18n/messages.d.ts (type-safe keys).
 * Chạy: pnpm --filter @ultimate/web i18n:gen
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { syncMessages, type Messages } from "../src/i18n/sync";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const viPath = path.join(root, "messages/vi.json");
const enPath = path.join(root, "messages/en.json");
const dtsPath = path.join(root, "src/i18n/messages.d.ts");

const vi = JSON.parse(readFileSync(viPath, "utf8")) as Messages;
let en: Messages = {};
try {
  en = JSON.parse(readFileSync(enPath, "utf8")) as Messages;
} catch {
  /* en.json chưa tồn tại — sinh mới toàn bộ */
}

const { result, added, removed } = syncMessages(vi, en);
writeFileSync(enPath, JSON.stringify(result, null, 2) + "\n");

const dts = `// GENERATED by scripts/i18n-gen.ts — KHÔNG sửa tay. Chạy: pnpm i18n:gen
type ViMessages = typeof import("../../messages/vi.json");
declare interface IntlMessages extends ViMessages {}
`;
writeFileSync(dtsPath, dts);

const todo = JSON.stringify(result).match(/__TODO__/g)?.length ?? 0;
console.log(`i18n:gen — thêm ${added.length}, xoá ${removed.length}, còn __TODO__: ${todo}`);
